#!/usr/bin/env python3

import subprocess
import sys
import urllib.parse

url = 'https://www.google.com/search?q='
sys.argv.pop(0)
query = urllib.parse.quote_plus(' '.join(sys.argv))
subprocess.run(['xdg-open', url+query], stdout=subprocess.DEVNULL)
