#!/bin/sh

remote="$1"
url="$2"
NEWLINE=$'\n'

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" != $z40 ]
	then
		if [ "$remote_sha" = $z40 ]
		then
			range="$local_sha"
		else
			range="$remote_sha..$local_sha"
		fi

		# check for invalid commit messages
		commits=`git rev-list --grep '^fixup! ' --grep 'squash! ' --grep '^# Conflicts:' "$range"`
		if [ -n "$commits" ]
		then
			echo "Found commits with invalid commit messages:$NEWLINE"
			for c in $commits
			do
				git show --no-patch $c
				echo $NEWLINE
			done
			exit 1
		fi
	fi
done

exit 0
