#!/bin/sh

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" != $z40 ]
	then
		if [ "$remote_sha" = $z40 ]
		then
			range="$local_sha"
		else
			range="`git merge-base $local_sha $remote_sha`..$local_sha"
		fi

		# check for invalid commit messages
		commits=`git rev-list --grep '^fixup! ' --grep 'squash! '  "$range"`
		if [ -n "$commits" ]
		then
			printf 'Found commits with invalid commit messages:\n'
			for c in $commits
			do
				git show --no-patch $c
				printf '\n'
			done
			exit 1
		fi
	fi
done

exit 0
