if has('gui_running')
	if has('mac')
		set guifont=Sauce\ Code\ Powerline:h12,Monaco:h10
	elseif has('unix')
		let fonts=['Source Code Pro for Powerline:Semibold 11', 'Misc Fixed:Medium Semi-Condensed 10', 'Ubuntu Mono:10']
		for font in fonts
			let font_parts = split(font, ':')
			if system('fc-match "' . font_parts[0] . '"') =~ font_parts[0]
				let &guifont = join(font_parts, ' ')
				break
			endif
		endfor
	elseif has('win32')
		set guifont=Consolas:h10:cDEFAULT
	endif

	set guioptions=
	set encoding=utf-8

	colorscheme solarized

	nnoremap <C-z> :shell<CR>
	inoremap <C-BS> <C-w>

	function! CheckPowerlineFont()
		if getfontname() =~ "Powerline"
			let g:airline_left_sep = ''
			let g:airline_left_alt_sep = ''
			let g:airline_right_sep = ''
			let g:airline_right_alt_sep = ''
			let g:airline_symbols.branch = ''
			let g:airline_symbols.readonly = ''
			let g:airline_symbols.linenr = ''
		endif
	endfunction

	augroup gui_enter
		autocmd!
		autocmd GUIEnter * call CheckPowerlineFont()
	augroup END
endif
