if has('gui_running')
	if has('mac')
		set guifont=Monaco\ 10
	elseif has('unix')
		set guifont=Fixed\ Medium\ Semi-Condensed\ 10
	elseif has('win32')
		set guifont=Consolas\ 10
	endif

	set guioptions-=e
	set guioptions-=m
	set guioptions-=T
	set encoding=utf-8

	colorscheme solarized

	inoremap <C-BS> <C-w>
endif
