#!/bin/sh

get_password () {
	protocol="$1"
	host="$2"
	username="$3"

	git credential fill <<-EOF | while IFS='=' read -r key value
	protocol=$protocol
	host=$host
	username=$username
	EOF
	do
		if test "$key" = 'password'
		then
			echo "$value"
			break
		fi
	done
}

password="$(get_password "$@")"
if test -z "$password"
then
	exit 1
fi

echo "set my_netrc_password = \"$password\""
